### PR TITLE
KPI M

### PR DESCRIPTION
**Pull request by martaguti**
Hi @wmo-im/tt-wismd , 
Please review and comment, I have updated the KPI with issues discussed during today's meeting. 

If happy with this version give it a thumbs up for merging to master.

### CODE REVIEW

**Comment by tomkralidis** [comment]
Thanks @martaguti.  Looks good to me. Note that I've added some minor changes in ae46bf3ddf084ca968f42a57457bccb93e30166c.

**Review by tomkralidis — APPROVED** [review]

**Comment by tomkralidis** [comment]
Update: related to one of today's actions on this KPI:

> Action: MG to review Part 2 on validating codelists

checking both WCMP 1.3, Part 2, and pywcmp, I didn't find anything that specifically requires to check all code list values, in which case we cannot rely on KPI A in this regard.  Once @martaguti can verify as well, then we can confirm KPI M is not duplicative to parts of KPI A.

**Comment by tomkralidis** [comment]
FYI minor updates to clean up merge conflicts.  Please review/comment/approve accordingly.

**Review by josusky — APPROVED** [review]

**Comment by martaguti** [comment]
@tomkralidis  there are no validations of codelists in Part 2 .  
Part 2 is only providing listings of codelists referenced in WCMP , and those are the ones that I included in KPI M for validation.
(as agreed in our last meeting we would not validate additional ISO codelists beyond the ones listed in Part 2 / KPI M ) or at least in our first iteration. 

From my side, KPI M is good to merge.

**Pull request merged**
