### PR TITLE
Prepare KPIs for Publication to WMO 1061 (#2)

### PR DESCRIPTION
**Pull request by amilan17**
#128

Note: do not merge until [all other tickets with `INFCOM-2` label](https://github.com/wmo-im/wcmp/pulls?q=is%3Aopen+is%3Apr+label%3AINFCOM-2) are merged.

### CODE REVIEW

**Comment by amilan17** [comment]
For first review
- [ ] rename of headers
- [ ] organization of sections
- [ ] addition of 000_intro1061.adoc

**Comment by amilan17** [comment]
yes, it's ok to number each rule in a KPI

**Review by josusky — APPROVED** [review]

**Comment by tomkralidis** [comment]
Thanks @josusky

@amilan17: let us know when your changes are completed so we can merge.

**Comment by amilan17** [comment]
This PR can be merged!

**Pull request merged**
