### PR TITLE
KPI C updates

### PR DESCRIPTION
**Pull request by tomkralidis**
This PR provides updates on KPI C.  Difficult KPI to implement programmatically, so I have placed "harder to measure" qualitative information as part of the last section.  @amilan17 can you provide the correct/current NOAA/EDM links so I can update accordingly?

As always, open to comments and suggestions on how to improve this KPI (note score values, overall, are pending discussion in #71).

### CODE REVIEW

**Comment by gaubert** [comment]
Here is one example of abstract generated for a bulletin (id: SIKB20NGTT) on the https://gisc.dwd.de

image

As you can see it should be quite easy to detect them

**Comment by tomkralidis** [comment]
Thanks @gaubert.  Can you/someone provide the actual trace on where this pattern comes from?  It would be valuable to provide reference to this "abstract bulletin template".  Thanks.

**Comment by tomkralidis** [comment]
P.S. other comments addressed per today's discussion.

**Comment by gaubert** [comment]
@tomkralidis it was initially generated by Meteo France if I remember correctly to start populating the catalogue with a GTS Bulletin description. It was automatically generated from VOL C which is meant to contain the bulletin description but is rarely updated and not update to date.
It would be good to have a negative point when it is there for a bulletin. 
What do you think.

**Comment by tomkralidis** [comment]
Thanks @gaubert .  KPI updated with negative scoring for bulletin template detection for review/comment.

**Review by amilan17 — CHANGES_REQUESTED** [review]
I think the guidance should be self containing and not refer to external resources, such as NOAA.

**Comment by tomkralidis** [comment]
Thanks @amilan17.  Done.

**Comment by tomkralidis** [comment]
Per [today's meeting](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-01-08), NOAA references removed.  Over to @martaguti to do cross reference check.

**Comment by martaguti** [comment]
@tomkralidis  checked WCMP Part1 / WMO Guidelines for abstract recommendations.
Added reference to the guidelines which contains good examples of abstracts.

**Pull request merged**
