### PR TITLE
KPI D updates

### PR DESCRIPTION
**Pull request by tomkralidis**
This PR provides updates on KPI D as per the discussion in #20.

As always, open to comments and suggestions on how to improve this KPI.

### CODE REVIEW

**Review by josusky — APPROVED** [review]

**Comment by josusky** [comment]
I agree with this KPI, it is time to take into account that official station identifier is the WIGOS ID (WSI). Having said that, I feel obliged to note that:
- Current manual on WIS either does not contain reference to WIGOS or it is formulated in a way that escapes my search trials.
- Not all data are station related, we should be clear o that not to frighten providers of other types of data.

**Comment by amilan17** [comment]
@tomkralidis -- can you remind me why this KPI is not included? I think it's important even though it was not included in WCMP 1.3.... Maybe we can add it as extra credit?

**Comment by amilan17** [comment]
not going to include in kpis for wcmp 1.3

**Comment by amilan17** [comment]
WIS Guide Reference: image

**Comment by tomkralidis** [comment]
Closing given focus on WCMP2 specification and KPIs as way forward.

**Pull request closed without merging**
