### PR TITLE
007-graphic-overview revisions

### PR DESCRIPTION
**Pull request by amilan17**

### CODE REVIEW

**Comment by amilan17** [comment]
change the title of this KPI -- NOT testing for non-bulletin, just testing if URL is good for graphics

**Comment by amilan17** [comment]
@wmo-im/tt-wismd - I changed this measurement and rules to ONLY test for the validity of the URL and not give a bad score when the graphic overview doesn't exist.

@josusky - can you change pywcmp?

**Review by josusky — APPROVED** [review]

**Comment by josusky** [comment]
> @wmo-im/tt-wismd - I changed this measurement and rules to ONLY test for the validity of the URL and not give a bad score when the graphic overview doesn't exist.
> 
> @josusky - can you change pywcmp?

There is nothing to change, it already works that way. When there is no `graphicOverview` element the KPI 7 does not influence the final score (summary). We could say that it is skiped - mathematically it is achieved by returning total 0 and score 0.

**Comment by amilan17** [comment]
*    [ ]  Review revision to rules

**Pull request merged**
